# Dockerfile para Frontend
FROM node:18

WORKDIR /app

# Copia o package.json e o package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código fonte
COPY . .

# Executa a build da aplicação Angular
RUN npm run build --prod

# Instala o http-server globalmente
RUN npm install -g http-server

# Expondo a porta 4200
EXPOSE 4200

# Comando para iniciar o http-server
CMD ["http-server", "dist/seu-projeto-angular", "-p", "4200"]
